name: Continuous Deployment to Google Cloud VM

on:
  push:
    branches: [ main ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Backend via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd /var/www/rentflow-api
            git pull origin main
            cd backend
            npm install --production
            npm run build
            pm2 restart 0

  deploy-frontend:
      name: Deploy Frontend
      runs-on: ubuntu-latest
      needs: deploy-backend # Opcional: si quieres que espere al backend
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20'

        - name: Install and Build
          run: |
            npm install
            npm run build

        # PASO NUEVO: Limpia el directorio en el servidor con sudo
        - name: Clean remote directory
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: sudo rm -rf /var/www/rentflow-frontend/*

        # PASO CORREGIDO: Copia los archivos sin el parámetro 'rm'
        - name: Copy files to server
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            source: "./dist/"
            target: "/var/www/rentflow-frontend"